export const mockTelegramWebApp = {
  ready: () => {},
  expand: () => {},
  close: () => {},
  MainButton: {
    text: "",
    color: "#000000",
    textColor: "#ffffff",
    isVisible: false,
    isActive: true,
    setText: () => {},
    onClick: () => {},
    offClick: () => {},
    show: () => {},
    hide: () => {},
    enable: () => {},
    disable: () => {},
  },
  BackButton: {
    isVisible: false,
    onClick: () => {},
    offClick: () => {},
    show: () => {},
    hide: () => {},
  },
  initDataUnsafe: {
    user: {
      id: 12345,
      first_name: "Test",
      last_name: "User",
      username: "testuser",
      language_code: "en",
      photo_url: "https://via.placeholder.com/100",
    },
  },
  themeParams: {
    bg_color: "#ffffff",
    text_color: "#000000",
    hint_color: "#999999",
    link_color: "#2481cc",
    button_color: "#2481cc",
    button_text_color: "#ffffff",
  },
  colorScheme: "light" as const,
};
